# Generated by Django 3.1.7 on 2021-03-17 12:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=30, verbose_name='Music Name')),
                ('musicactor', models.CharField(max_length=20, verbose_name='Music Actor')),
                ('musicyear', models.CharField(max_length=4, verbose_name='Music Year')),
                ('musiccontent', ckeditor.fields.RichTextField(max_length=400, verbose_name='Music Content')),
                ('musicfile', models.FileField(blank=True, null=True, upload_to='', verbose_name='Music Photo')),
            ],
        ),
    ]
