# Generated by Django 3.1.7 on 2021-03-17 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmusic',
            name='musiccontent',
            field=ckeditor.fields.RichTextField(max_length=600, verbose_name='Music Content'),
        ),
    ]
